- direction: 'horizontal'
- name: 'edge only'
  service: 'valve_edge_grasp_only'
  image: "package://drc_task_common/icons/valve-edge.png"
  image_size: [80, 80]
  column: 0
- name: 'edge preferred'
  service: 'valve_edge_grasp_preferred'
  image: "package://drc_task_common/icons/valve-edge.png"
  image_size: [80, 80]
  column: 0
  default_value: True
- name: 'center preferred'
  service: 'valve_center_grasp_preferred'
  image: "package://drc_task_common/icons/valve-center.png"
  image_size: [80, 80]
  column: 0
- name: 'center only'
  service: 'valve_center_grasp_only'
  image: "package://drc_task_common/icons/valve-center.png"
  image_size: [80, 80]
  column: 0
- name: 'enable-head-overwrite'
  service: 'enable_head_overwrite'
  image: "package://drc_task_common/icons/enable-head-overwrite.png"
  image_size: [100, 100]
  column: 1
- name: 'disable-head-overwrite'
  service: 'disable_head_overwrite'
  image: "package://drc_task_common/icons/disable-head-overwrite.png"
  image_size: [100, 100]
  column: 1
  default_value: True
